MLK-15098: ASoC: fsl: fix imx-pcm build error when no dma cherry-picked from: http://git.freescale.com/git/cgit.cgi/imx/linux-imx.git/commit/?h=imx_4.9.11_1.0.0_ga&id=87096594094e5a02586cbdc84ee2b6f5a2c9138b
Fix build error when SOC_IMX_PCM_DMA is not enabled
error: expected identifier or ‘(’ before ‘{’ token})

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
(cherry picked from commit 67ee27e3c97c8deb851ca61fab0e513009b93dbe)